services:
  server:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8082:80
    networks:
      - app-network
    volumes:
      - ./dist/:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/

networks:
  app-network:
    driver: bridge